export const products = [
    'Apple',
    'Watermelon',
    'Orange',
    'Pear',
    'Strawberry',
    'Grape',
    'Plum',
    'Mango',
    'Blueberry',
    'Papaya',
    'Apricot',
    'Mandarin',
    'Banana',
    'Grapefruit',
    'Lemon',
    'Lime',
    'Pineapple',
    'Jackfruit',
    'Melon',
    'Coconut',
    'Avocado',
    'Peach',
    'Kiwi',
    'Blackcurrant',
    'Blackberry',
    'Cherry',
    'Fig',
    'Lychee',
    'Nectarine',
    'Passionfruit',
    'Quince',
    'Raspberry',
    'Tangerine',
    'Pomegranate',
    'Mulberry',
    'Starfruit',
    'Guava',
    'Pomelo',
    'Cranberry',
    'Tamarillo',
    'Curuba',
    'Soursop',
    'Uchuva',
    'Honeymelon',
    'Granadilla',
    'Durian',
    'Dragon fruit',
    'Longan',
    'Rambutan',
    'Tamarind',
    'Persimmon',
    'Mangosteen',
    'Amla',
    'Cucumber',
    'Onion',
    'Garlic',
    'Carrot',
    'Red cabbage',
    'White cabbage',
    'Radish',
    'Eggplant',
    'Mushroom',
    'Artichoke',
    'Corn',
    'Broccoli',
    'Cauliflower',
    'Celery',
    'Red chili',
    'Green chili',
    'Sweet potato',
    'Asparagus',
    'Pumpkin',
    'Fennel',
    'Springonion',
    'Turnip',
    'Lettuce',
    'Zucchini',
    'Brussels sprout',
    'Tomato',
    'Potato',
    'Pea',
    'Spinach',
    'Beetroot',
    'Bellpepper',
    'Leek',
    'Ginger',
    'Squash',
    'Coriander',
    'Napacabbage',
    'Arugula',
    'Kale',
    'Rutabaga',
    'Yam',
    'Bitter melon',
    'Taro',
    'Kohlrabi',
    'Bean sprouts',
    'Chicken',
    'Turkey',
    'Beef',
    'Pork',
    'Mutton',
    'Ham',
    'Fish',
    'Seafruit',
    'Egg',
    'Yoghurt',
    'Milk',
    'Cereals',
    'Oats',
    'Sugar',
    'Brown sugar',
    'Flour',
    'Chocolate',
    'Cream',
    'Sourcream',
    'Olive oil',
    'Sunflower oil',
    'Vegetable oil'
]
